name: Deploy to GitHub Pages

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  schedule:
    - cron: '30 12 * * *'  # Every day at 12:30 PM UTC
  workflow_dispatch:
  
permissions:
  contents: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: eu-west-2
  
    - name: Pull labnotes result
      id: pull_labnotes
      run: |
        # Generate date path (YYYY/MM/DD format)
        DATE_PATH=$(date +"%Y/%m/%d")
        echo "Publishing to path: $DATE_PATH"
        
        # Download file from S3
        aws s3 cp s3://labnotes-storage/$DATE_PATH/summarised_results.json ./public/summarised_results.json || echo "No labnotes file found"
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'
        
    - name: Install dependencies
      run: npm ci
      
    - name: Generate SEO files (sitemap & RSS)
      run: npm run generate:seo

    - name: Build
      run: npm run build
      env:
        VITE_CALENDLY_URL: ${{ vars.VITE_CALENDLY_URL }}
        VITE_EMAIL: ${{ vars.VITE_EMAIL }}
        VITE_LINKEDIN_URL: ${{ vars.VITE_LINKEDIN_URL }}
        VITE_GA_MEASUREMENT_ID: ${{ vars.VITE_GA_MEASUREMENT_ID }}

    - name: Replace URLs
      run: grep -rl "giovannidoni.github.io" ./dist | xargs sed -i 's|/giovannidoni.github.io/|/|g'

    - name: Add .nojekyll file
      run: touch dist/.nojekyll
        VITE_GOOGLE_VERIFICATION_CONTENT: ${{ vars.VITE_GOOGLE_VERIFICATION_CONTENT }}
        VITE_GOOGLE_VERIFICATION_FILENAME: ${{ vars.VITE_GOOGLE_VERIFICATION_FILENAME }}
        
    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      if: github.ref == 'refs/heads/main'
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./dist